= Introduction
<introduction>

== Overview

The solar wind is a hot, magnetized plasma that continuously expands from the solar corona into interplanetary space, driven by the pressure gradient between the dense coronal plasma and the surrounding interstellar medium @parkerDynamicsInterplanetaryGas1958 @parkerDynamicalTheorySolar1965 @velliSupersonicWindsAccretion1994 @velliHydrodynamicsSolarWind2001. As it propagates outward, the solar wind accelerates to super-Alfvénic speeds, transporting mass, momentum, and energy throughout the heliosphere.
Because the solar wind is highly electrically conductive, magnetic field lines are frozen into the plasma flow to a good approximation. The resulting large-scale interplanetary magnetic field (IMF) is shaped by the combination of radial expansion and solar rotation, producing the Archimedean spiral geometry described by the Parker model---a configuration well supported by observations when averaged over sufficiently long intervals @zhaoStatisticsInterplanetaryMagnetic2025 @zhaoStatisticsInterplanetaryMagnetic2025a.

#figure(
  image("figures/ref/smith2001-fig2.png", width: 60%),
  caption: [
    Three-dimensional representation of the HCS inside the heliosphere. The tilt of the solar magnetic dipole relative to the rotation axis causes the current sheet to form a warped, spiraling surface that a spacecraft near the ecliptic crosses twice per solar rotation @jokipiiEffectsDriftTransport1981.
  ],
) <fig-intro-hcs-3d>

The most prominent large-scale structure arising from this magnetic topology is the heliospheric current sheet (HCS)---the thin surface separating open field lines of opposite polarity @smithHeliosphericCurrentSheet2001. The dipole tilt and solar rotation warp this surface into a spiraling "ballerina-skirt" geometry (@fig-intro-hcs-3d) that extends throughout the heliosphere. In situ, the HCS manifests as a sharp IMF polarity reversal; Parker Solar Probe observations confirm this structure persists from close to the Sun out to 1 AU, with the large-scale geometry remaining stable while the small-scale plasma structures surrounding the sheet evolve substantially during outward propagation (@fig-intro-hcs-comparison) @szaboHeliosphericCurrentSheet2020.

#figure(
  image("figures/ref/szabo2020-fig5.jpg"),
  caption: [
    Comparison of HCS crossings observed by PSP and Wind with the PSP data forward shifted and magnetic field scaled. The upper two panels are the PSP 315 eV electron PADs (in flux units and normalized) propagated to the location of Wind. The next two panels are the 265 eV Wind electron PADs. The bottom three panels show the Wind observed magnetic field (green) and scaled PSP measurements (red) in spherical coordinates. Vertical dotted lines show the time of the propagated PSP HCS events
    // Comparison of HCS crossings observed by PSP and by Wind at 1 au (green overlays) for 14 crossings during the first PSP encounter. Each row shows the electron PAD and scaled magnetic field azimuth, with the PSP time axis shifted to account for propagation to Wind's location. The good agreement in large-scale sector polarity and crossing timing demonstrates the global stability of the HCS between the inner heliosphere and 1 au, while differences in small-scale structure indicate significant evolution of meso-scale features during outward propagation @szaboHeliosphericCurrentSheet2020.
  ],
) <fig-intro-hcs-comparison>

Superposed on this ordered background, however, are fluctuations spanning a broad range of scales and magnitudes. These fluctuations are a manifestation of magnetohydrodynamic (MHD) turbulence @schekochihinMHDTurbulenceBiased2022@matthaeusTurbulenceSpacePlasmas2021@brunoTurbulenceSolarWind2016@brunoSolarWindTurbulence2013@tuMHDStructuresWaves1995@goldsteinMagnetohydrodynamicTurbulenceSolar1995, which is multi-scale, intermittent, and strongly non-Gaussian @chandranIntermittentReflectiondrivenStrong2025@brunoIntermittencySolarWind2019@verscharenMultiscaleNatureSolar2019@matthaeusIntermittencyNonlinearDynamics2015. A key feature of this turbulence is that energy does not distribute uniformly across space as it cascades from large to small scales. Instead, it concentrates into localized, coherent structures --- magnetic flux ropes, magnetic holes, plasma waves, and current sheets @perroneCoherentEventsIon2020@khabarovaCurrentSheetsPlasmoids2021@pezziCurrentSheetsPlasmoids2021 --- which actively feed back into the plasma, contributing to heating, particle acceleration, and departures from classical MHD behavior @degiorgioCoherentStructureFormation2017@borovskyContributionStrongDiscontinuities2010@liEffectCurrentSheets2011@grecoPartialVarianceIncrements2017.

Among these coherent structures, current sheets---thin layers of intense electric current where the magnetic field direction changes abruptly---are the most prominent and dynamically significant (see @observations-of-solar-wind-current-sheets for a comprehensive review). First identified in Pioneer 6 measurements as sharp directional changes in the interplanetary magnetic field @nessPreliminaryResultsPioneer1966@colburnDiscontinuitiesSolarWind1966, they were initially classified within the MHD discontinuity framework as tangential discontinuities (separating topologically distinct plasma regions with no normal field component) or rotational discontinuities (propagating Alfvénic structures connecting magnetically linked regions) @hudsonDiscontinuitiesAnisotropicPlasma1970. The relative abundance of these two discontinuity types and their physical significance for magnetic topology have been subjects of longstanding debate (see @from-mhd-discontinuities-to-kinetic-scale-current-sheets) @neugebauerCommentAbundancesRotational2006. High-resolution measurements from missions such as ARTEMIS, MMS, and Parker Solar Probe have since revealed that many current sheets possess fundamentally kinetic properties: their thicknesses are on the order of a few ion inertial lengths, and their internal structure---including temperature anisotropy and non-gyrotropic ion distributions---defies a purely MHD description @artemyevKineticNatureSolar2019@vaskoKineticscaleCurrentSheets2022. Statistically, current sheets are ubiquitous throughout the heliosphere, with occurrence rates exceeding 100 events per day at 1 AU @zhangSolarWindDiscontinuities2025a (see @sec-occurrence-rate). Their normalized properties---thickness in units of the ion inertial length and current density in units of the Alfvén current density---exhibit a pronounced inverse correlation (stronger currents in thinner sheets) that extends over several orders of magnitude (see @sec-scale_density), suggesting a universal feature of the turbulent cascade @vaskoKineticScaleCurrentSheets2024. The observational characterization of these properties across the inner heliosphere is developed in @solar-wind-discontinuities-in-the-outer-heliosphere-spatial-distribution-between-1-and-5-au and @comparison-of-solar-wind-current-sheets-in-the-inner-heliosphere.

The heliosphere thus presents two interleaved levels of magnetic organization: the ordered global structure of the Parker spiral and HCS, and the smaller-scale turbulence and coherent structures embedded within that background. This multiscale magnetic environment strongly influences heliophysics processes, especially the transport of energetic particles. Large-scale topology determines magnetic connectivity while small-scale structures govern local scattering and confinement.

Solar energetic particles (SEPs) are high-energy ions and electrons episodically accelerated in the solar and interplanetary environment @anastasiadisSolarEnergeticParticles2019@kleinAccelerationPropagationSolar2017@desaiLargeGradualSolar2016@reamesTwoSourcesSolar2013 (see @energetic-particles-in-the-heliosphere). They originate either in the low solar corona during eruptive events (impulsive SEP events, associated with magnetic reconnection in solar flares), or at interplanetary shock fronts driven by fast coronal mass ejections (gradual SEP events, driven by diffusive shock acceleration) @reamesTwoSourcesSolar2013@desaiLargeGradualSolar2016. SEP events pose radiation hazards to spacecraft electronics, astronauts, and high-altitude aviation, and they provide a natural laboratory for studying particle acceleration and transport in magnetized plasmas---with implications extending to astrophysical systems more broadly.

Two contrasting observational signatures of SEP transport provide particularly compelling evidence for the role of magnetic structures in controlling particle propagation (see @reservoir-and-dropout-phenomena for a detailed discussion). The reservoir effect---in which widely separated spacecraft observe nearly identical particle intensities and spectral shapes during the decay phase of large gradual events @reamesTwoSourcesSolar2013@dallaPropertiesHighHeliolatitude2003 ---implies substantial cross-field transport that distributes particles throughout a large heliospheric volume. In contrast, dropout events---abrupt depletions of particle intensity at current sheet crossings @mazurInterplanetaryMagneticField2000@tesseinEffectCoherentStructures2015 ---indicate that particles can be effectively confined within individual magnetic flux tubes, with current sheets acting as barriers at their boundaries. Together, these phenomena reveal a fundamental duality: current sheets can both impede and facilitate particle transport, depending on their internal structure and the particle energy.

#figure(
  image("figures/ref/reamesTwoSourcesSolar2013-fig6.png"),
  caption: [
    The reservoir effect in solar energetic particle events. Left: proton intensities at several energies measured by Wind/LEMT during the 1997 November 6 event, showing uniform decay profiles across energies after the initial rise. Right: energy spectra at successive times remain nearly identical in shape (invariant spectra), indicating that particles have filled a large heliospheric volume and are decaying uniformly. Bottom: schematic of spacecraft positions relative to the Sun. Such spatially uniform distributions imply substantial cross-field transport, potentially mediated by interactions with current sheets and other coherent structures @reamesTwoSourcesSolar2013.
  ],
)
<fig-intro-reservoir>

The standard theoretical framework for SEP propagation is the quasi-linear theory (QLT) of pitch-angle scattering @jokipiiCosmicRayPropagationCharged1966 (see @turbulence-transport-frameworks), which treats the turbulent magnetic field as a superposition of small-amplitude, randomly phased waves and derives diffusion coefficients from the resonant interaction between particles and fluctuations at the cyclotron frequency. However, growing observational and numerical evidence demonstrates that the fine-scale magnetic structure of the solar wind---in particular, its coherent, intermittent character---can exert a decisive influence on particle dynamics that QLT does not capture @malaraEnergeticParticleDynamics2023@malaraChargedparticleChaoticDynamics2021@artemyevSuperfastIonScattering2020.

When a particle's gyroradius becomes comparable to the thickness of a current sheet, the standard guiding-center approximation fails because the magnetic field varies on scales smaller than the gyro-orbit. In this regime, the magnetic moment $mu$ is no longer the appropriate conserved quantity. Instead, the dynamics are governed by the quasi-adiabatic invariant $I_z$---the action variable of the fast oscillation normal to the current sheet @zelenyiQuasiadiabaticDynamicsCharged2013@buchnerRegularChaoticCharged1989 (see @quasi-adiabatic-dynamics-of-charged-particles-and-its-destruction-in-current-sheets for the full theoretical development). This invariant is approximately conserved during regular motion but undergoes jumps at separatrix crossings in phase space, where the particle transitions between qualitatively different types of oscillation (e.g., from gyration on one side of the sheet to figure-eight orbits spanning both sides). In symmetric current sheets without a guide field, these jumps are small and accumulate diffusively. However, in force-free current sheets---where the intermediate magnetic field component peaks at the center, breaking the phase-space symmetry---geometrical chaotization produces order-unity jumps in $I_z$ within a single interaction @artemyevRapidGeometricalChaotization2014@artemyevSuperfastIonScattering2020 (see @geometrical-chaotization-rapid-destruction-independent-of-kappa and @application-to-force-free-solar-wind-current-sheets-superfast-scattering). Since $I_z$ determines the particle's oscillation amplitude and thus its pitch angle, the destruction of $I_z$ is physically equivalent to pitch-angle scattering---but through a "superfast" mechanism fundamentally distinct from, and potentially more efficient than, wave--particle resonance. Because current sheets are abundant throughout the heliosphere and their thickness overlaps with the gyro-radii of suprathermal and energetic ions, such interactions are not rare events but a systematic feature of SEP propagation.

Despite their importance, a quantitative understanding of how current sheets influence SEP transport has remained incomplete, for two reasons. First, the statistical properties of kinetic-scale current sheets---their occurrence rate, thickness distribution, and internal magnetic configuration---have not been systematically characterized across different regions of the heliosphere. Second, the connection between these microphysical structural properties and macroscopic transport coefficients has not been rigorously established. This dissertation addresses both gaps.

Specifically, this dissertation (1) develops a coherent observational framework to characterize the properties and occurrence rates of current sheets across heliocentric distances from 0.17 to 5 AU @zhangSolarWindDiscontinuities2025a@zhangComparisonSolarWind2026, and (2) constructs a quantitative model of pitch-angle scattering and spatial transport of energetic particles driven by current sheets, parameterized by the observed statistical distributions @zhangQuantificationIonScattering2025. Together, these contributions bridge the microphysics of individual current sheet encounters and the macroscopic diffusion of energetic particles through the heliosphere, offering new insight into heliospheric particle dynamics and a foundation for improved space weather prediction.
