#let equation-numbering = "(1)"

= Quantification of Particle Scattering by Solar Wind Current Sheets: Pitch-angle Diffusion Rates
<quantification-of-particle-scattering-by-solar-wind-current-sheets-pitch-angle-diffusion-rates>
Current sheets---coherent structures arising from the turbulent energy cascade---act as efficient scatterers of energetic particles in collisionless plasmas @artemyevSuperfastIonScattering2020@malaraChargedparticleChaoticDynamics2021@degiorgioCoherentStructureFormation2017@perroneCoherentEventsIon2020. Because they are ubiquitous throughout the heliosphere, their interaction with energetic particles is a systematic rather than incidental feature of particle transport, with implications for SEP modeling @desaiLargeGradualSolar2016@giacaloneCosmicrayTransportInteraction2013.

Despite extensive research on magnetic turbulence @pucciEnergeticParticleTransport2016@oughtonSolarWindTurbulence2021, the quantitative impact of coherent structures on particle transport remains insufficiently explored. Previous studies have primarily focused on idealized turbulence models @giacaloneTransportCosmicRays1999@matthaeusNonlinearCollisionlessPerpendicular2003, often neglecting the specific role of coherent structures, such as current sheets, in the scattering of energetic particles. Investigations of interactions between rotational discontinuities (or groups of such discontinuities forming so-called switchbacks; see @baleHighlyStructuredSlow2019@witSwitchbacksNearsunMagnetic2020) and energetic particles have demonstrated highly chaotic particle dynamics @malaraChargedparticleChaoticDynamics2021@malaraEnergeticParticleDynamics2023. However, previous studies focused on elucidating the basic mechanisms rather than quantifying scattering using realistic distributions in accordance with observations. This study aims to bridge that gap by providing a detailed analysis and quantification of particle interactions with current sheets, building on the observational characterization of current sheet properties across the inner heliosphere developed in @solar-wind-discontinuities-in-the-outer-heliosphere-spatial-distribution-between-1-and-5-au and @comparison-of-solar-wind-current-sheets-in-the-inner-heliosphere. We adopt an analytical model of the magnetic field configuration that incorporates realistic statistical parameters derived from solar wind observations at 1 AU. By leveraging an exact Hamiltonian formulation that accounts for the rotational effects of the magnetic field, alongside test particle simulations, we investigate the evolution of particle pitch angles and the statistical long-term behavior of pitch-angle scattering across different particle energies. This approach allows us to extend prior works @whitmanReviewSolarEnergetic2023 about energetic particle modeling and references therein by incorporating realistic coherent structures.

The structure of this paper is as follows. In #ref(<sec-equations>, supplement: [Section]) we present a detailed description of the magnetic field model and the fundamental equations governing particle motion. In #ref(<sec-adiabatic-invariance>, supplement: [Section]) we introduce the concept of adiabatic invariance and discuss its violations due to separatrix crossings in phase space. #ref(<sec-simulations>, supplement: [Section]) presents numerical simulation results and statistical observations of current sheets in the solar wind. In #ref(<sec-evolution>, supplement: [Section]) we analyze the long-term evolution of particle pitch angles due to multiple scatterings by current sheets. Finally, a discussion and conclusions are provided in #ref(<sec-conclusion>, supplement: [Section]).

== Basic Equations
<sec-equations>
We assume the following 1-D force-free ($B = c o n s t$) magnetic field configuration where $upright(bold(B))$ depends only on the $z$ coordinate across the current sheet surface:

$
  upright(bold(B)) = B \( cos theta med upright(bold(e_z)) + sin theta \( sin phi \( z \) med upright(bold(e_x)) + cos phi \( z \) med upright(bold(e_y)) \) \) \,
$

where $B$ is the magnitude of the magnetic field, and $theta$ is the azimuthal angle between the normal $upright(bold(B_z)) = B cos theta med upright(bold(e_z)) equiv B_n upright(bold(e_z))$ and the magnetic field. More specifically, we assume the following form: $phi \( z \) = beta tanh \( z \/ L \)$, where $L$ is the thickness of the current sheet and the shear half-angle $beta$ is one half of the in-plane rotation angle $omega_(i n)$. The transverse magnetic field $upright(bold(B_t)) = B_t sin phi \( z \) med upright(bold(e_x)) + B_t cos phi \( z \) med upright(bold(e_y))$ rotates by an angle $omega_(i n)$ from $- oo$ to $+ oo$ where $B_t = B sin theta$. As an example, we present an observation from the ARTEMIS mission @angelopoulosARTEMISMission2011, which captures a magnetic field transition consistent with our model. #ref(<fig-ARTEMIS>, supplement: [Figure]) shows the variations in $upright(bold(B))$, $theta$, and $phi$ across the current sheet. The transverse field rotates smoothly, with $phi$ following a hyperbolic tangent profile (note that time is linearly proportional to the spatial coordinate $z approx v_n t$ where $v_n$ is the solar wind velocity along the normal to the current sheet surface), while $theta$ remains nearly constant near $pi \/ 2$, indicating a small normal component $B_n$. (A three-dimensional visualization of a typical current sheet magnetic field structure, represented by the magnetic field line, together with three representative particle trajectories is provided in #ref(<fig-B_diagram_particle_trajectory>, supplement: [Figure]).)

#figure(
  image("figures/scattering/thc.pdf"),
  caption: [
      Example of a current sheet observed by ARTEMIS@angelopoulosARTEMISMission2011. Top: magnetic field in the current sheet #strong[lmn] coordinate system @sonnerupMinimumMaximumVariance1998 where $l$ represents the maximum variance direction ($B_x = B_t sin phi$ in our model), $m$ the intermediate variance direction ($B_y = B_t cos phi$), and $n$ the minimum variance direction ($B_z = B cos theta$). Here, $B_t$ and $B$ represent the tangential and total magnetic fields, respectively (see text for detailed definitions). Bottom: variations of the azimuthal angle $phi$ and the azimuthal angle $theta$ across the current sheet. Vertical lines indicate the current sheet boundaries, and the horizontal line represents $pi \/ 2$. The analysis is based on magnetic field data with a 0.25-second resolution from the Fluxgate Magnetometer @austerTHEMISFluxgateMagnetometer2008.
    ]
)
<fig-ARTEMIS>


The motion of a charged particle in a pure magnetic field is governed by the Hamiltonian:

$ H = frac(1, 2 m) (upright(bold(p)) - q upright(bold(A)))^2 $

where $upright(bold(A))$ represents the magnetic vector potential and $upright(bold(p))$ the canonical momentum. In the context of our model, the magnetic vector potential $upright(bold(A))$ admits the following integrable form:

$
  A_x & = L B_t f_1 \( z \) \
  A_y & = L B_t f_2 \( z \) + x B_n \
  A_z & = 0
$

#math.equation(block: true, numbering: equation-numbering, [ $
  f_1 & \( z \) = 1 / 2 cos beta med [upright("Ci") (beta s_(+) \( z \)) - upright("Ci") (beta s_(-) \( z \))] \
      & + 1 / 2 sin beta med [upright("Si") (beta s_(+) \( z \)) - upright("Si") (beta s_(-) \( z \))] \, \
  f_2 & \( z \) = 1 / 2 sin beta med [upright("Ci") (beta s_(+) \( z \)) + upright("Ci") (beta s_(-) \( z \))] \
      & - 1 / 2 cos beta med [upright("Si") (beta s_(+) \( z \)) + upright("Si") (beta s_(-) \( z \))]
$ ])<eq-Hamiltonian>

and $s_plus.minus \( z \) = 1 plus.minus tanh \( z \/ L \)$, $upright("Ci")$ and $upright("Si")$ are the cosine and sine integral functions @abramowitzHandbookMathematicalFunctions1972.

We introduce a dimensionless Hamiltonian $tilde(H) = H \/ h$ by normalizing $\( x \, z \) = \( tilde(x) L + C_x \, tilde(z) L \)$ and $\( p_x \, p_z \) = p \( tilde(p_x) \, tilde(p_z) \)$ where $p = q L B_t \/ c$ and $h = q^2 L^2 B_t^2 \/ m c^2$. Note that because $partial H \/ partial y = 0$, $p_y = upright("const")$ and we could let $C_x = c p_y \/ q B_n$ to eliminate $p_y$:

$ tilde(H) = 1 / 2 ((tilde(p_x) - f_1 \( z \))^2 + (tilde(x) cot theta + f_2 \( z \))^2 + tilde(p_z)^2) $

This is an exact Hamiltonian of a charged particle, incorporating the effect of magnetic field rotation characterized by the shear angle $beta$. Unlike previous studies that rely on Taylor expansions near the current sheet center $z = 0$ @vainchteinQuasiadiabaticDescriptionNonlinear2005@artemyevIonMotionCurrent2013@zelenyiQuasiadiabaticDynamicsCharged2013, we retain the full, unexpanded form. However, for comparison, we note that expanding the Hamiltonian to third order around the current sheet center and assuming $beta = 1$ yields a reduced form structurally similar to that used in #cite(<artemyevSuperfastIonScattering2020>, form: "prose"), albeit with a different normalization scheme. In this study, we quantitatively investigate the influence of shear half-angle ($beta$) and particle energy ($E = H \/ h$) on the efficiency of pitch-angle scattering. For simplicity, the tilde notation over dimensionless variables is omitted in the following discussion.

== Adiabatic invariance and its violations at separatrix crossings
<sec-adiabatic-invariance>
For current sheets where $B_n \/ B_t lt.double 1$, the variables $\( kappa x \, p_x \)$ evolve significantly more slowly compared to $\( z \, p_z \)$ along particle trajectories (with $dot(p)_x prop kappa$, where $kappa = cot theta$). Assuming that $x$ and $p_x$ are effectively frozen, the Hamiltonian describes periodic motion within the $\( z \, p_z \)$ plane, governed by the effective potential energy $U \( z \) = H - p_z^2 \/ 2$. When variations in $\( kappa x \, p_x \)$ occur on a timescale much longer than the fast oscillations in $\( z \, p_z \)$, the generalized magnetic moment $I_z = \( 2 pi \)^(- 1) integral.cont p_z d z$ is approximately conserved as an adiabatic invariant with exponential accuracy @neishtadtAccuracyPersistenceAdiabatic2000. Far from the current sheet, where the magnetic field is nearly uniform ($abs(z \/ L) gt.double 1$), the pitch angle defined by $alpha = arccos upright(bold(B)) dot.op upright(bold(v)) \/ abs(upright(bold(B))) abs(upright(bold(v)))$ remains constant (i.e., $partial alpha \/ partial upright(bold(r)) = 0$), where $upright(bold(v))$ is the velocity, $upright(bold(B))$ is the magnetic field, and $r$ is the position. Since the simultaneous conservation of energy and $I_z$ fully determines the motion of the particle, the velocity $upright(bold(v))$ can be expressed as a function of position $upright(bold(r))$, invariant $I_z$, and energy $E$: $upright(bold(v)) = upright(bold(v)) \( upright(bold(r)) \, I_z \, H \)$. Given that energy is exactly conserved in a static magnetic field, the pitch angle $alpha$ depends solely on $I_z$. Therefore, in the absence of $I_z$ destruction, there is no pitch-angle scattering across the current sheet.

#figure(
  image("figures/scattering/fig-bcPlot.pdf"),
  caption: [
      \(a) Phase portraits of the Hamiltonian in the plane of $\( z \, p_z \)$ at fixed $\( kappa x \, p_x \)$ for $beta = 1$. Each curve corresponds to a specific $H$, indicated on the plots. The left panel corresponds to $kappa x = 4$, $p_x = 1$, while the right panel corresponds to $kappa x = 0$, $p_x = 0.5$. (b) Phase plane of the Hamiltonian in the $\( kappa x \, p_x \)$ space. The red line represents the uncertainty curve and the blue line delineates the boundary encompassing all possible phase points. (c) Potential energy profiles defined by $U \( z \) = H - p_z^2 \/ 2$ at different locations in the $\( kappa x \, p_x \)$ place, corresponding to the labeled positions (\#) in panel (b).
    ]
)
<fig-zPz_phase>
#pagebreak(weak: true)

The Hamiltonian admits two distinct types of particle motion in the $\( z \, p_z \)$ plane, as illustrated in #ref(<fig-zPz_phase>, supplement: [Figure])\(a). In the left panel, there are two potential wells in $U \( z \)$, resulting in three possible types of orbits in the $\( z \, p_z \)$ plane depending on the value of $H$: particles can move (oscillate) within one of local $U \( z \)$ minima, or can move outside these minima along #emph[figure-eight] orbits. In contrast, the right panel represents a case with only one possible type of orbits in the $\( z \, p_z \)$ plane for a fixed $H$. As $\( kappa x \, p_x \)$ evolve slowly, the particle's trajectory in the $\( z \, p_z \)$ plane undergoes a gradual transformation. Transitions between motion types can occur, accompanied by significant trajectory reconfigurations when the particle crosses the separatrix, the curve separating motion within one of two local minima of $U \( z \)$ and motion along #emph[eight-like] orbit (separatrix is shown by red bold line in #ref(<fig-zPz_phase>, supplement: [Figure])\(a)). Near the separatrix, the instantaneous period of motion in the $\( z \, p_z \)$ plane increases logarithmically, diverging as the trajectory approaches it @lichtenbergRegularStochasticMotion1983. When the timescale (period) of fast oscillations in the $\( z \, p_z \)$ plane and variations in the control parameter ($kappa x$) become comparable, the particle accumulates a nonvanishing change in the adiabatic invariant, resulting in a jump in $I_z$ @neishtadtChangeAdiabaticInvariant1999@caryAdiabaticinvariantChangeDue1986. Concurrently, the projection of the particle's phase point onto the $\( kappa x \, p_x \)$ plane lies along the so-called uncertainty curve #ref(<fig-zPz_phase>, supplement: [shown by red bold line in]), where each point on the curve corresponds to a particle trajectory in ($z \, p_z$) coinciding with the separatrix.

The jump of $I_z$ due to the separatrix crossing comprises two distinct components. The first component, termed the #emph[dynamical jump], arises from the singularity of the period of motion in the vicinity of the separatrix and, in our asymmetric case of the $\( z \, p_z \)$ plane about the $z$-axis (stemming from the term in $f_1$) is proportional to $kappa ln kappa$ @neishtadtMechanismsDestructionAdiabatic2019[and references therein], resulting in slight changes to particle trajectories. The second component, referred to as the #emph[geometric jump], corresponds to the difference between the areas enclosed by the particle's trajectory within one of the separatrix wells and the area in the external region outside the separatrix. For instance, when a particle drifts from the boundary immediately before crossing, the total area enclosed by the separatrix increases to the value of the adiabatic invariant, $I_0 = \( 2 pi \)^(- 1) S \( kappa x \, p_x \)$. Upon crossing, the adiabatic invariant $I_z$ undergoes a jump to approximately the area of the left well $S_l \( kappa x \, p_x \)$ or the right well $S_r \( kappa x \, p_x \) = S \( kappa x \, p_x \) - S_l \( kappa x \, p_x \)$, reflecting the reduction in the accessible phase space area for the particles. This geometric jump is independent of $kappa$ and of order unity @neishtadtMechanismsDestructionAdiabatic2019[and references therein]. For a single separatrix crossing and small values of $kappa$, this jump of adiabatic invariance arises primarily from geometric destruction @artemyevSuperfastIonScattering2020. In symmetric Hamiltonians -- where $U \( - z \) = U \( z \)$ -- the differences in the enclosed areas during two successive crossings effectively cancel: the area deficit incurred when entering one of two wells is offset by the excess upon exiting, so that the net geometric jump over two crossings is zero @neishtadtChangeAdiabaticInvariant1999@buchnerRegularChaoticCharged1989. However, in our case, the term $f_1 \( z \)$ introduces an asymmetry in the $\( z \, p_z \)$ plane #ref(<fig-zPz_phase>, supplement: [see]), leading to an asynchronous evolution of the two areas. As a result, the difference in areas at each crossing does not cancel between successive crossings. This produces a nonzero change in $I_z$ that enhances pitch-angle scattering and drives rapid chaotization of the particle dynamics @artemyevIonMotionCurrent2013@artemyevSuperfastIonScattering2020. %Although the dynamical jumps tend to average out to zero @neishtadtChangeAdiabaticInvariant1999@buchnerRegularChaoticCharged1989 for two successive crossings occur, the uncompensated geometric jumps accumulate, producing a nonzero net change in $I_z$ that enhances pitch-angle scattering and drives rapid chaotization of the particle dynamics @artemyevIonMotionCurrent2013.

Due to the symmetry of particle motion about the $p_z = 0$ line, the potential energy $U \( z \)$ reaches a local maximum along the $z$-direction at the saddle point $z = z_c \, p_z = 0$ of the separatrix (shown as $z_c$ in Fig. (left panel)). At this point, conditions $partial U \/ partial z = 0$ and $partial^2 U \/ partial z^2 < 0$ are satisfied. These conditions allow us to express the slow variables along the uncertainty curve in the $\( kappa x \, p_x \)$ plane as functions of $z_c$. When a particle trajectory crosses the $z = 0$ plane, the crossing point is confined within a circular region defined by $\( p_x - f_1 \( 0 \) \)^2 + \( kappa x + f_2 \( 0 \) \)^2 = 2 H$. The likelihood of the trajectory intersecting the uncertainty curve is therefore approximately proportional to the uncertainty curve length $L_(upright("uc"))$, normalized by the square root of the particle energy, $sqrt(H)$, as illustrated in #ref(<fig-UCLength>, supplement: [Figure]). For fixed $H$, $L_(upright("uc")) \/ sqrt(H)$ increases with $beta$, indicating higher scattering probabilities at larger magnetic field rotation angles. Similarly, at a fixed $beta$, $L_(upright("uc")) \/ sqrt(H)$ increases with $H$, suggesting that high-energy particles are more susceptible to pitch-angle scattering. Next, we will demonstrate these changes using test particles in realistic fields, to characterize their properties as functions of system parameters.

#figure(
  image("figures/scattering/UCLength.pdf"),
  caption: [
      The uncertainty curve length $L_(upright("uc")) \/ sqrt(H)$ as a function of $beta$ and normalized particle energy $H$.
    ]
)
<fig-UCLength>


== Test particle simulations
<sec-simulations>
To quantitatively analyze how particles are scattered by solar wind current sheets, we conducted extensive test particle simulations using a dataset of solar wind current sheets at 1 AU. Since the primary focus is on protons, the particle mass was set to $m_p$ (proton mass) and the charge to the elementary charge $q = e$. According to the dimensionless Hamiltonian, the critical current sheet parameters that influence particle dynamics are angles $theta$ and $beta = omega_(i n) \/ 2$, along with the parameter $B_t L$, which appears in the normalization factors $p$ and $h = frac(q^2 L^2 B_t^2, m c^2)$. By a simple transformation, $B_t = B sin theta$, the key current sheet parameters become $theta$, $omega_(i n)$, and $tilde(v)_B equiv v_B \/ c$, where $v_B equiv q B L \/ \( m_p c \) = Omega L$ and $Omega$ is the proton gyrofrequency associated with the magnetic field $B$.

#figure(
  image("figures/scattering/wind_hist3d.png"),
  caption: [
      3D density plots of the azimuthal angle $theta$, in-plane rotation angle $omega_(i n)$, and logarithm of the characteristic velocity $log tilde(v)_B$. The left panel corresponds to cases where the MVAB accuracy conditions are satisfied, while the right panel represents cases where they are not satisfied.
    ]
)
<fig-windHist3D>


Using data from the ARTEMIS @angelopoulosARTEMISMission2011 and the Wind mission @acunaGlobalGeospaceScience1995, we compiled a dataset of 100000 current sheets @zhangSolarWindDiscontinuities2025@liuMagneticDiscontinuitiesSolar2022. The orientations of these current sheets were determined using the minimum variance analysis of the magnetic field (MVAB) method @sonnerupMinimumMaximumVariance1998. Accurate orientation determination was crucial for estimating the thickness of the current sheets ($L$) and the in-plane magnetic field rotation angle ($omega_(i n)$), both of which significantly influence particle scattering. To ensure reliability, only current sheets with $Delta abs(B) \/ abs(B) > 0.05$ or $omega > 60 degree$ were used in the following analysis, as these conditions improve the accuracy of the MVAB method, as noted by . Note, these conditions do not constrain the discontinuity normal. An alternative approach to orientation determination @wangSolarWindCurrent2024@knetterFourpointDiscontinuityObservations2004 involves using the cross-product method to estimate the normal orientation and is largely based on the assumption that $B_n$ is effectively zero.
#ref(<fig-windHist3D>, supplement: [Figure]) shows 3D density plots of the azimuthal angle $theta$, the in-plane rotation angle $omega_(i n)$, and logarithm of the characteristic velocity $log tilde(v)_B$, categorized by whether the MVAB accuracy conditions are satisfied (left for accurate, right for not accurate). Current sheets with accurately determined orientations typically have smaller azimuthal angles $theta$, indicating a smaller $B_n$, and moderate in-plane rotation angles $omega_(i n)$. In contrast, current sheets with potentially inaccurate normal orientations display larger $theta$ (larger $B_n$) and larger $omega_(i n)$. The most probable values observed in the distribution are a characteristic velocity ($v_B$) of approximately 500 km/s (which corresponds to a typical energy $tilde.op 1$ keV), an in-plane rotation angle ($omega_(i n)$) near 100 degrees, and an azimuthal angle ($theta$) around 85-95 degrees.

For each magnetic field configuration, we initialize an ensemble of particles far away from the current sheet center (i.e., with an initial $z$ position satisfying $\| z_0 \| > 6 L + 2 r_g$, where $r_g$ is the gyro radius). The particles are uniformly binned in pitch angle ($alpha_0$) from $0^compose$ to $180^compose$ in 180 bins of size $Delta alpha = 1^compose$, with gyro phase ($psi_0$) uniformly sampled from $0^compose$ to $360^compose$ in 120 bins of size $Delta psi = 3^compose$. In this simulation, the current sheet is consistently configured with a positive $B_z$ component. Consequently, particles with an initial positive pitch-angle cosine $mu equiv cos alpha$ ($alpha_0 < 90^compose$\; $mu_0 > 0$) are interpreted to originate below the current sheet (and move toward the current sheet), while those with a negative cosine ($alpha_0 > 90^compose$\; $mu_0 < 0$) are considered to come from above it (and move toward the current sheet). The particle trajectories are then numerically integrated until each particle fully exits the current sheet ($\| z \( t \) \| > \| z_0 \| + 2 r_g$). #ref(<fig-B_diagram_particle_trajectory>, supplement: [Figure]) shows three representative particle trajectories in a typical magnetic field configuration characterized by $beta = 75^compose$ and $theta = 85^compose$. All particles have the same initial pitch angle $alpha_0 = 90^compose$ and velocity $v_p = 8 v_B$, but differ slightly in their initial gyrophases: $phi.alt_0 = 163.3^compose \, 164.4^compose$, and $165.6^compose$.
These cases illustrate distinct scattering behaviors: one particle exhibits a negligible change in pitch angle, another undergoes a finite pitch-angle deflection, and the third is reflected by the current sheet. For each trajectory, the final pitch angle $alpha_1$ is recorded. These pitch angles are then organized into bins to construct a transition matrix (TM), also known as a stochastic matrix @durrettEssentialsStochasticProcesses2016, which represents the probability distribution of pitch-angle changes resulting from a single particle interaction with the current sheet.

#figure(
  image("figures/scattering/fig-B_diagram_particle_trajectory.pdf"),
  caption: [
      Three particle trajectories (T1, T2, T3) with identical initial pitch angles ($alpha_0 = 90^compose$) and velocity $v_p = 8 v_B$, but slightly different initial gyrophases ($phi.alt_0 = 163.3^compose \, 164.4^compose \, 165.6^compose$) in a representative magnetic field profile ($beta = 75^compose \, theta = 85^compose$). The orange star marks the initial particle position. The black and gray lines represent the magnetic field lines to which the reflected particle (T3) is initially and finally attached, respectively, before and after interaction with the current sheet.
    ]
)
<fig-B_diagram_particle_trajectory>
#pagebreak(weak: true)

#ref(<fig-tm-example>, supplement: [Figure]) illustrates the transition matrix for 100 keV particles (velocity $v_p approx 4000$ km/s) under four magnetic field configurations: (i) $v_B = 500$ km/s, $theta = 85 degree$, $beta = 50 degree$\; (ii) $v_B = 500$ km/s, $theta = 85 degree$, $beta = 75 degree$\; (iii) $v_B = 500$ km/s, $theta = 60 degree$, $beta = 50 degree$\; and (iv) $v_B = 4000$ km/s, $theta = 85 degree$, $beta = 50 degree$. Enhanced probability along the diagonal corresponds to weakly scattered particles ($laplace alpha = alpha_1 - alpha_0 approx 0$), while spreading around the diagonal reflects diffusive scattering. Large pitch-angle jumps are represented by non-diagonal elements.

#figure(
  image("figures/scattering/example_subset.pdf"),
  caption: [
      Transition matrix for 100 keV protons under four distinct magnetic field configurations: (i) $v_p = 8 v_B$, $theta = 85 degree$, $beta = 50 degree$\; (ii) $v_p = 8 v_B$, $theta = 85 degree$, $beta = 75 degree$\; (iii) $v_p = 8 v_B$, $theta = 60 degree$, $beta = 50 degree$\; and (iv) $v_p = v_B$, $theta = 85 degree$, $beta = 50 degree$.
    ]
)
<fig-tm-example>

The transition matrix color maps for various current sheet configurations reveal that particle pitch-angle evolution during multiple current sheet crossings is determined by a combination of weak/strong diffusion and large jumps. For example, in current sheets with a typical shear half-angle $beta = 50 degree$ and azimuthal angle $theta = 85 degree$ (configuration (i)), particles entering from above the sheet ($z > 0$\; assuming positive $B_n$) often experience significant pitch-angle jumps or strong diffusion. In contrast, particles entering from below the sheet ($z < 0$) typically undergo minimal pitch-angle changes. Occasionally, interactions with current sheets having very large shear half-angles ($beta$, e.g., configuration (ii)) or smaller azimuthal angles ($theta$, e.g., configuration (iii)) result in enhanced diffusion and the reflection of certain particles from the current sheet, indicated by a reversal in the sign of $cos alpha$. For high-energy particles, interactions with current sheets of comparable characteristic speed ($v_B tilde.op v_p$, configuration (iv)) are characterized by weak scattering occurring only over a narrow range of pitch angles. The interplay between non-diffusive jumps and continuous diffusive processes drives a dynamic evolution of the particle ensemble. %Over time, this leads to a broadened and redistributed pitch-angle profile, reflecting the statistical nature of interactions with solar wind current sheets.

== Long-term pitch angle evolution
<sec-evolution>
Modeling the long-term effect of particle pitch-angle scattering by current sheets involves simulating the dynamics of a large number of particles through multiple current sheet interactions over extended periods. To reduce computational time and complexity of such simulations and introduce scattering effects into existing transport models, we derive a simplified probabilistic description of pitch-angle evolution.
The scattering process depends on the particle's initial conditions, $\( upright(bold(r)) \, upright(bold(v)) \)$, as well as the configuration of the current sheet, $upright(bold(B))$. In the 1D model, these initial conditions can be expressed in terms of $z \, E_0 \, alpha_0$, and $psi_0$. Since our primary interest lies in the pitch angle after the particle exits the current sheet, and the energy $E_0$ remains constant in the absence of an electric field, the initial energy $E_0$ and position $z$ (provided that the particle is sufficiently far from the center of the current sheet) can be omitted from further consideration.

The final pitch angle, however, is highly sensitive to initial conditions $\( alpha_0 \, psi_0 \)$, where small variations in the gyro phase can lead to significantly different final pitch angles @malaraChargedparticleChaoticDynamics2021. Therefore, the scattering process $Pi : \( alpha_0 \, psi_0 \) arrow.r \( alpha_1 \, psi_1 \)$ is better represented as a probabilistic transition $p \( alpha_1 \| alpha_0 \, Pi \)$, with the probability derived by numerical interpolation in the $alpha_1$-space. Here, $Pi$ characterizes the current sheet configuration. This probabilistic representation is further motivated by the fact that the gyro phase depends on the particle's location and may undergo random shifts during the crossing of a current sheet. Additionally, numerical integration methods, such as the Boris method, introduce a phase error proportional to $Delta t$, making the gyro phase less reliable. Thus, it is more appropriate to model the gyro phase as a random variable. This probabilistic approach eliminates the dependence on the gyro phase, instead focusing on the statistical relationship between the initial pitch angle $alpha_0$ and the final pitch angle $alpha_1$, as governed by the properties of the current sheets.

For particles with a specific energy, a (weighted-average) mixture distribution @fruhwirth-schnatterFiniteMixtureMarkov2006 can be constructed based on the observed distribution of solar wind discontinuities (SWDs): $p \( alpha_1 \| alpha_0 \) = sum_i p \( alpha_1 \| alpha_0 \, Pi_i \) w_i$, where the weight $w_i$ corresponds to the empirical probabilities of specific SWD configurations. After binning, this yields a weighted transition matrix (WTM), which represents the varying likelihoods of particles encountering Sw Ds with different properties and encapsulates the overall probability of a particle undergoing a pitch-angle jump due to interactions with an ensemble of SWDs at 1 AU.

As illustrated in #ref(<fig-tm-stats-100keV>, supplement: [Figure]), the WTM for 100 keV protons at 1 AU shows a strong likelihood of minimal changes in pitch angle, as evidenced by the bright diagonal. However, there exist significant probabilities associated with diffusive scattering and with large pitch-angle changes. The latter arise mainly from interactions with current sheets whose characteristic scales ($L$) are comparable to or smaller than the gyroradius of (in this case) 100 keV protons. Such strong scattering cannot be adequately described by diffusion alone. However, the mapping described in Equation\~ enables the direct application of the mixture distribution for simulating the long-term evolution of particle pitch-angle distributions (such map is a discretized approximation of stochastic differential equations that describe particle dynamics with a given scattering probability; see @jacodDiscretizationProcesses2012@ukhorskiyRoleDriftOrbit2011@artemyevMappingNonlinearElectron2020@tonoianElectronResonantInteraction2023):


#math.equation(block: true, numbering: equation-numbering, [ $
  alpha_(n + 1 \, i) = W_Pi (alpha_(n \, i) \, xi_(n \, i))
$ ])<eq-mapping>

where $n$ is the number of interactions (with SWDs), $i$ is the particle index within the ensemble, and $W_Pi$ determines the subsequent pitch angle from the mixture distribution, using the previous pitch angle and a uniformly sampled random variable $xi_(n \, i)$.

#pagebreak(weak: true)
#figure(
  image("figures/scattering/tm_stats_100keV.pdf"),
  caption: [
      Weighed transition matrix for 100 keV particles constructed from the observed distribution of current sheet at 1 AU.
    ]
)
<fig-tm-stats-100keV>
#pagebreak(weak: true)

#ref(<fig-pa-jump-history>, supplement: [Figure]) illustrates two representative solutions of the dynamical pitch-angle mapping equation derived from the mixture distribution at 1 AU for 100 keV and 1 MeV protons. A key feature of the pitch-angle dynamics is the occurrence of infrequent but substantial jumps, including rare, large-angle changes that can lead to particle reflection from the current sheet.

#figure(
  image("figures/scattering/pa_jump_history_high.pdf"),
  caption:[
      Examples of particle pitch-angle scattering by solar wind current sheets for 100 keV and 1 MeV protons.
    ]
)
<fig-pa-jump-history>


However, directly incorporating the mapping (or stochastic difference equations) derived from the mixture distribution into classical numerical schemes for transport-diffusion equations is a complex task (see discussion in @litvinenkoNumericalStudyDiffusive2013@straussHitchhikersGuideStochastic2017@mykhailenkoSDEMethodCosmic2024). To facilitate comparison with other scattering processes and allow inclusion of SWD-induced scattering effects in such models, we evaluate the effective scattering rate, $D_(mu mu)$. This rate acts as a global diffusion coefficient, independent of the local pitch angle, since high-energy particles frequently experience large pitch-angle jumps, leading to strong mixing. The scattering rate depends on the particle energy and the mixture distribution (i.e., the distribution of current sheets). Using the mapping described in Equation\~ for an ensemble of particles, we calculate the evolution of the second moment of the pitch-angle distribution for the particle energy range from 100 keV to 1 MeV for current sheets at 1 AU:

$
  M_1 \( n \) = N^(- 1) sum_(i = 1)^N \( alpha_(n \, i) - alpha_(0 \, i) \)\
  M_2 \( n \) = N^(- 1) sum_(i = 1)^N \( alpha_(n \, i) - alpha_(0 \, i) \)^2 - M_1^2 \( n \)
$

where $M_1 \( n \)$ represents the mean drift in pitch-angle, and $M_2 \( n \)$ quantifies the spreading in pitch-angle. The function $M_2 \( n \)$ increases linearly with the number of interactions with current sheets before reaching saturation, where the pitch-angle distribution becomes totally mixed. This behavior is illustrated in #ref(<fig-mixing-rate>, supplement: [Figure]). The rate of such mixing is described by $D_(mu mu)$, which can be evaluated by fitting $M_2 \( n \)$ to an exponential model, $M_2 \( n \) = d - a e^(- D_(mu mu) n)$, where $d$ is the saturated second moment and $a$ is the slope of the exponential fit. This model assumes that at early stages (small $n$), particles undergo diffusive mixing, with $M_2 \( n \) prop D_(mu mu) n$. At later stages (large $n$), the distribution becomes fully mixed, and $M_2$ asymptotically approaches a constant value, $M_2 approx M_2 \( oo \)$.

To translate the number of interactions $n$ into a physical time, we consider the occurrence rate of SWD @vaskoKineticscaleCurrentSheets2022@zhangSolarWindDiscontinuities2025 and the average solar wind speed. Using these parameters, we can estimate the average distance between SWDs. Assuming that protons travel freely between interactions at velocities $v_p tilde.op sqrt(H)$, we can then derive the characteristic time interval between consecutive encounters with discontinuities. This enables the transition from a discrete interaction-based framework ($D_(mu mu)$) to a continuous temporal description ($cal(D)_(mu mu)$), making it suitable for realistic modeling of particle dynamics and enabling direct incorporation of derived diffusion rates into transport-diffusion simulations.
This approach provides a simplified yet effective means to account for current-sheet-induced scattering in broader models of energetic particle dynamics.

#figure(
  image("figures/scattering/mixing_rate.pdf"),
  caption: [
      Top: Second moment of the pitch-angle distribution, $M_2 \( n \)$, as a function of interaction number ($n$) for different particle energies (100 eV, 5 keV, 100 keV, 1 MeV), The estimated mixing rates, $D_(mu mu)$, are indicated in the legend. Bottom: Pitch-angle diffusion rates $cal(D)_(mu mu)$ as a function of particle energy $E$.
    ]
)
<fig-mixing-rate>


== Conclusion
<sec-conclusion>
In this study, we have investigated the scattering of energetic particles by current sheets in the solar wind and developed a model that incorporates the rotational effects $beta$, the magnetic field magnitude $B$, and the current sheet thickness $L$. Our findings indicate that current sheets characterized by large rotation angles or relatively small characteristic velocities, defined as $tilde(v)_B = frac(q B L, m c^2)$, can effectively scatter energetic particles. These scattering effects go beyond the conventional diffusion framework, as large pitch-angle jumps lead to rapid particle mixing in pitch-angles. Leveraging extensive observations of solar wind current sheets at 1 AU, we have provided a statistical estimate that quantifies the long-term scattering rate of energetic particles due to current sheets.

In the heliosphere, beyond 1AU, the background magnetic field strength decreases approximately as $tilde.op 1 \/ r$ with increasing radial distance, where the azimuthal component $B_phi.alt$ dominates and $B approx B_phi.alt tilde.op 1 \/ r$. The magnitude of the current sheet magnetic field ($B$) scales accordingly with the background field @zhangSolarWindDiscontinuities2025. Based on recent observations, the current sheet thickness, $L$, scales with the ion inertial length, $d_i prop 1 \/ sqrt(N)$, which increases with radial distance due to the decline in plasma density, $N prop 1 \/ r^2$ @marucaTransHeliosphericSurveyRadial2023. Consequently, the characteristic velocity $tilde(v)_B prop B L$ remains nearly constant with the radial distance, implying that energetic particles consistently undergo significant scattering by current sheets as they propagate through the heliosphere. The higher occurrence rate of current sheets closer to the Sun @liuCharacteristicsInterplanetaryDiscontinuities2021@lotekarKineticscaleCurrentSheets2022 implies an even more pronounced impact on the transport of solar energetic particles.

These findings may have significant implications for the dynamics of energetic particles in both space and astrophysical plasmas. The extension of these scattering results to spatial transport---both parallel and perpendicular---is developed in @energetic-particle-transport-driven-by-solar-wind-current-sheets. Efficient pitch-angle scattering enhances the ability of particles to reverse direction along magnetic field lines, thereby reducing their tendency to stream freely and limiting parallel transport. In quasi-linear theory, the parallel spatial diffusion coefficient is approximately inversely proportional to the pitch-angle diffusion coefficient for resonant interactions @engelbrechtTheoryCosmicRay2022@jokipiiCosmicRayPropagationCharged1966@jokipiiAddendumErratumCosmicRay1968. Additionally, observations frequently reveal broad spatial distributions of solar energetic particles and the formation of particle reservoirs @cohenSolarEnergeticParticles2021, suggesting either reduced diffusion rates along magnetic field lines or highly efficient cross-field diffusion @zhangPropagationSolarEnergetic2009. Our results indicate that the pitch-angle scattering due to current sheets can significantly affect parallel and perpendicular transport, and this point will be addressed in future work.

== Data availability
<data-availability>
The code and data used for the findings and figures in this study are available at #link("https://github.com/Beforerr/ion_scattering_by_SWD"). ARTEMIS and Wind data are available at NASA's Space Physics Data Facility (SPDF) #link("https://spdf.gsfc.nasa.gov").
