== Thesis Organization
<thesis-organization>
The remainder of this chapter reviews the observational and theoretical background in two parts. @observations-of-solar-wind-current-sheets reviews the observational properties of solar wind current sheets, including identification and characterization methods, their kinetic nature, and the statistical characteristics reported in the literature. @energetic-particle-interaction-with-solar-wind-current-sheets introduces the solar energetic particle context: the sources and classification of SEP events, the transport frameworks within which pitch-angle scattering is parameterized, and the motivation---rooted in solar wind intermittency---for going beyond classical quasi-linear theory; it develops the quasi-adiabatic theory of particle motion near magnetic field reversals and the mechanisms by which the quasi-adiabatic invariant is destroyed at separatrix crossings.

The body of the thesis is then organized into two parts. #strong[Part I] (@solar-wind-discontinuities-in-the-outer-heliosphere-spatial-distribution-between-1-and-5-au @zhangSolarWindDiscontinuities2025 and @comparison-of-solar-wind-current-sheets-in-the-inner-heliosphere @zhangComparisonSolarWind2026) presents the observational characterization of kinetic-scale current sheets across the inner heliosphere from a coordinated set of spacecraft: Parker Solar Probe (PSP) at distances as close as 0.17 AU, Wind, ARTEMIS, and STEREO near 1 AU, and Juno during its cruise phase out to 5 AU. These chapters systematically quantify the statistical distributions of current sheet thickness and current density---two parameters that directly determine the magnetic field configuration experienced by energetic particles. A central finding is that the normalized properties of current sheets (thickness in units of the ion inertial length, current density in units of the Alfvén current density) are largely invariant from 0.17 to 5 AU, implying that the scattering environment for energetic particles maintains a consistent character throughout the inner heliosphere. The observational results therefore provide the empirical foundation for the particle-transport studies that follow.

#strong[Part II] (@quantification-of-particle-scattering-by-solar-wind-current-sheets-pitch-angle-diffusion-rates and @energetic-particle-transport-driven-by-solar-wind-current-sheets) investigates how kinetic-scale current sheets scatter and transport energetic particles. @quantification-of-particle-scattering-by-solar-wind-current-sheets-pitch-angle-diffusion-rates @zhangQuantificationIonScattering2025 develops an exact Hamiltonian formulation for particle motion in force-free current sheets and quantifies pitch-angle scattering through test-particle simulations parameterized by the observed distributions from Part I. The scattering is shown to be dominated by infrequent but large pitch-angle jumps---a non-Brownian process driven by geometrical chaotization---rather than continuous diffusion. @energetic-particle-transport-driven-by-solar-wind-current-sheets extends this analysis to spatial transport, showing that the perpendicular-to-parallel diffusion ratio increases with particle energy and can exceed standard quasi-linear predictions, with implications for the broad spatial distributions observed in SEP events. Together, these chapters bridge the microphysics of individual current sheet encounters and macroscopic heliospheric transport.

@summary-and-future-perspectives summarizes the principal findings and discusses open questions and future directions, with emphasis on the origins of solar wind current sheets and on strategies for incorporating intermittency effects into SEP transport models.

Two appendices present complementary developments that support the main results. @multifluid-equilibrium-model @zhangMultifluidEquilibriumModel2026 introduces a multi-fluid current sheet model developed to interpret the plasma velocity structure and sub-unity Alfvénicity observed in the current sheet catalogs of Part I; it is constructed to allow non-zero normal magnetic field components while maintaining constant magnetic field magnitude, thereby extending beyond simplified one-dimensional MHD configurations. @juliaspacePhysics-ecosystem describes the Julia-based software ecosystem that underpins the large-scale statistical analyses and test-particle simulations performed throughout this work, enabling performant and interactive scientific exploration.
